myShopBackControllers.controller('ordersController', function($scope, appDataSv) {
    $scope.ordersModel = {
      orderlist:{},//全部订单
      queryAllOrder:function(){
        appDataSv.query(global.server.queryAllOrder,{},function(data){
          if(global.status.success==data.status){
            $scope.ordersModel.orderlist=data.data;
            console.info(data.data);
          }
        });
      },
      waitlist:{
        status:1,
      },//等待发货
      queryWaitList:function(){
        appDataSv.query(global.server.queryStatus,{status:$scope.ordersModel.waitlist.status},function(data){
          if(global.status.success==data.status){
            $scope.ordersModel.waitlist=data.data;
            console.info(data.data);
          }
        });
      },
      paylist:{
        status:2,
      },//等待发货
      queryPayList:function(){
        appDataSv.query(global.server.queryStatus,{status:$scope.ordersModel.paylist.status},function(data){
          if(global.status.success==data.status){
            $scope.ordersModel.paylist=data.data;
            console.info(data.data);
          }
        });
      },
      checklist:{
        status:3,
      },//等待发货
      queryCheckList:function(){
        appDataSv.query(global.server.queryStatus,{status:$scope.ordersModel.checklist.status},function(data){
          if(global.status.success==data.status){
            $scope.ordersModel.checklist=data.data;
            console.info(data.data);
          }
        });
      },
      all:function(){//全部订单
        $("#allOrder").removeClass("hide");
        $("#searchOrder").addClass("hide");
        $("#all").removeClass("hide");
        $("#wait").addClass("hide");
        $("#onroad").addClass("hide");
        $("#check").addClass("hide");
      },
      wait:function(){//等待发货
        $("#allOrder").removeClass("hide");
        $("#searchOrder").addClass("hide");
        $("#all").addClass("hide");
        $("#wait").removeClass("hide");
        $("#onroad").addClass("hide");
        $("#check").addClass("hide");
      },
      onroad:function(){//等待收货
        $("#allOrder").removeClass("hide");
        $("#searchOrder").addClass("hide");
        $("#all").addClass("hide");
        $("#wait").addClass("hide");
        $("#onroad").removeClass("hide");
        $("#check").addClass("hide");
      },
      check:function(){//交易成功
        $("#allOrder").removeClass("hide");
        $("#searchOrder").addClass("hide");
        $("#all").addClass("hide");
        $("#wait").addClass("hide");
        $("#onroad").addClass("hide");
        $("#check").removeClass("hide");
      },
      send:function(){return $("#order_send")},
      sendTo:function(orderid){//点击发货
          appDataSv.save(global.server.sendTo,{orderid:orderid},function(data){
            if(global.status.success==data.status){
              console.info(111);
                $scope.ordersModel.send().modal();
            }
          });
      },
      allStatus:function(orderid,status){
        if(status=="待发货"){
          appDataSv.save(global.server.sendTo,{orderid:orderid},function(data){
            if(global.status.success==data.status){
              console.info(111);
                $scope.ordersModel.send().modal();
            }
          });
        }
      },
      restart:function(){
        window.location.reload();
      },
      searchForm:{
        orderid:'',
        ordertime:''
      },//查询列表
      searchDetail:{},
      findOrder:function(){//查询订单
        appDataSv.save(global.server.findOrder,{orderid:$scope.ordersModel.searchForm.orderid,ordertime:$scope.ordersModel.searchForm.ordertime},function(data){
          if(global.status.success==data.status){
            $scope.ordersModel.searchDetail=data.data;
            console.info(data.data);
            // $("#allOrderMenu").addClass("hide");
            $("#allOrder").addClass("hide");
            $("#searchOrder").removeClass("hide");
          }
        });
      }
    };
    $scope.ordersModel.queryAllOrder();
    $scope.ordersModel.queryWaitList();
    $scope.ordersModel.queryPayList();
    $scope.ordersModel.queryCheckList();
    $('#date').fdatepicker();
    $(function(){
      $('.order_detail_menu ul li').click(function(){
        $(this).addClass('active').siblings().removeClass('active');
        // $('.orders').eq($(this).index()).addClass('in active').siblings().removeClass('in active');
      });
    });
});
